# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-15 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0005_auto_20191115_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='login_registration_app.User'),
            preserve_default=False,
        ),
    ]
